<?php

return [
    'Aceh' => [
        'Meulaboh',
        'Blangpidie',
        'Jantho',
        'Calang',
        'Tapak Tuan',
        'Singkil',
        'Karang Baru',
        'Takengon',
        'Kutacane',
        'Idi Rayeuk',
        'Lhoksukon',
        'Simpang Tiga Redelong',
        'Bireuen',
        'Blang Kejeren',
        'Suka Makmue',
        'Sigil',
        'Meureudu',
        'Sinabang',
        'Banda Aceh',
        'Langsa',
        'Lhokseumawe',
        'Sabang',
        'Subulussalam'
    ],
    'Sumatera Utara' => [
        'Kisaran',
        'Limapuluh',
        'Sidikalang',
        'Lubuk Pakam',
        'Dolok Sanggul',
        'Kabanjahe',
        'Rantau Prapat',
        'Kota Pinang',
        'Aek Kanopan',
        'Stabat',
        'Panyabungan',
        'Gido',
        'Lahomi',
        'Teluk Dalam',
        'Lotu',
        'Sibuhuan',
        'Gunung Tua',
        'Salak',
        'Pangururan',
        'Sei Rampah',
        'Raya',
        'Sipirok',
        'Pandan',
        'Tarutung',
        'Balige',
        'Kota Binjai',
        'Gunungsitoli',
        'Kota Medan',
        'Padangsidimpuan',
        'Pematangsiantar',
        'Tanjungbalai',
        'Tebing Tinggi'
    ],
    'Sumatera Barat' => [
        'Lubuk Basung',
        'Pulau Punjung',
        'Tuapejat',
        'Sarilamak',
        'Parit Malintang',
        'Lubuk Sikaping',
        'Simpang Ampek',
        'Painan',
        'Muaro Sijunjung',
        'Arosuka',
        'Padang Aro',
        'Batusangkar',
        'Bukittinggi',
        'Padang',
        'Padangpanjang',
        'Pariaman',
        'Payakumbuh',
        'Sawahlunto',
        'Solok'
    ],
    'Riau' => [
        'Bengkalis',
        'Tembilahan',
        'Rengat',
        'Bangkinang',
        'Selatpanjang',
        'Teluk Kuantan',
        'Pangkalan Kerinci',
        'Bagansiapiapi',
        'Pasir Pengaraian',
        'Siak Sri Indrapura',
        'Dumai',
        'Pekanbaru'
    ],
    'Jambi' => [
        'Muara Bulian',
        'Muara Bungo',
        'Siulak',
        'Sengeti',
        'Sarolangun',
        'Kuala Tungkal',
        'Muara Sabak',
        'Muara Tebo',
        'Jambi',
        'Sungaipenuh'
    ],
    'Sumatera Selatan' => [
        'Manna',
        'Karang Tinggi',
        'Arga Makmur',
        'Bintuhan',
        'Kepahiang',
        'Muara Aman',
        'Mukomuko',
        'Curup',
        'Tais',
        'Bengkulu',
        'Pangkalan Balai',
        'Tebing Tinggi',
        'Lahat',
        'Muara Enim',
        'Sekayu',
        'Muara Beliti Baru',
        'Rupit',
        'Indralaya',
        'Kota Kayu Agung',
        'Baturaja',
        'Muaradua',
        'Martapura',
        'Talang Ubi',
        'Lubuklinggau',
        'Pagar Alam',
        'Palembang',
        'Prabumulih'
    ],
    'Bengkulu' => [
        'Manna',
        'Karang Tinggi',
        'Arga Makmur',
        'Bintuhan',
        'Kepahiang',
        'Muara Aman',
        'Mukomuko',
        'Curup',
        'Tais',
        'Bengkulu'
    ],
    'Lampung' => [
        'Pangkalan Balai',
        'Tebing Tinggi',
        'Lahat',
        'Muara Enim',
        'Sekayu',
        'Liwa',
        'Kalianda',
        'Gunung Sugih',
        'Sukadana',
        'Kotabumi',
        'Mesuji',
        'Gedong Tataan',
        'Krui',
        'Pringsewu',
        'Kota Agung',
        'Menggala',
        'Tulang Bawang Tengah',
        'Blambangan Umpu',
        'Bandar Lampung',
        'Kota Metro'
    ],
    'Kepulauan Bangka Belitung' => [
        'Sungailiat',
        'Muntok',
        'Koba',
        'Tanjung Pandan',
        'Manggar',
        'Pangkal Pinang'
    ],
    'Kepulauan Riau' => [
        'Kijang',
        'Tanjung Balai Karimun',
        'Tarempa',
        'Daik',
        'Ranai',
        'Batam',
        'Tanjungpinang'
    ],
    'DKI Jakarta' => [
        'Pulau Pramuka',
        'Kembangan',
        'Menteng',
        'Kebayoran',
        'Cakung',
        'Koja'
    ],
    'Jawa Barat' => [
        'Soreang',
        'Ngamprah',
        'Cikarang',
        'Cibinong',
        'Ciamis',
        'Cianjur',
        'Sumber',
        'Tarogong Kidul',
        'Indramayu',
        'Karawang',
        'Kuningan',
        'Majalengka',
        'Parigi',
        'Purwakarta',
        'Subang',
        'Palabuhanratu',
        'Sumedang',
        'Singaparna',
        'Bandung',
        'Banjar',
        'Bekasi',
        'Bogor',
        'Cimahi',
        'Cirebon',
        'Depok',
        'Sukabumi',
        'Tasikmalaya'
    ],
    'Jawa Tengah' => [
        'Purwokerto',
        'Batang',
        'Blora',
        'Boyolali',
        'Brebes',
        'Cilacap',
        'Demak',
        'Purwodadi',
        'Jepara',
        'Karanganyar',
        'Kebumen',
        'Kendal',
        'Klaten',
        'Kudus',
        'Mungkid',
        'Pati',
        'Kajen',
        'Pemalang',
        'Purbalingga',
        'Purworejo',
        'Rembang',
        'Ungaran',
        'Sragen',
        'Sukoharjo',
        'Slawi',
        'Temanggung',
        'Wonogiri',
        'Wonosobo',
        'Magelang',
        'Pekalongan',
        'Semarang',
        'Surakarta',
        'Tegal'
    ],
    'DI Yogyakarta' => [
        'Bantul',
        'Sleman',
        'Gunung Kidul',
        'Yogyakarta'
    ],
    'Jawa Timur' => [
        'Bangkalan',
        'Banyuwangi',
        'Kanigoro',
        'Bojonegoro',
        'Bondowoso',
        'Gresik',
        'Jember',
        'Jombang',
        'Ngasem',
        'Lamongan',
        'Lumajang',
        'Caruban',
        'Magetan',
        'Kepanjen',
        'Mojosari',
        'Nganjuk',
        'Ngawi',
        'Pacitan',
        'Pamekasan',
        'Bangil',
        'Ponorogo',
        'Kraksaan',
        'Sampang',
        'Sidoarjo',
        'Situbondo',
        'Sumenep',
        'Trenggalek',
        'Tuban',
        'Tulungagung',
        'Kota Batu',
        'Blitar',
        'Kediri',
        'Madiun',
        'Malang',
        'Mojokerto',
        'Pasuruan',
        'Probolinggo',
        'Surabaya',
        'Madura'
    ],
    'Banten' => [
        'Rangkasbitung',
        'Pandeglang',
        'Ciruas',
        'Tigaraksa',
        'Cilegon',
        'Serang',
        'Tangerang',
        'Tangerang Selatan'
    ],
    'Bali' => [
        'Bangli',
        'Singaraja',
        'Gianyar',
        'Negara',
        'Amlapura',
        'Semarapura',
        'Tabanan',
        'Denpasar'
    ],
    'Nusa Tenggara Barat' => [
        'Woha',
        'Kalabahi',
        'Atambua',
        'Ende',
        'Larantuka',
        'Oelamasi',
        'Lewoleba',
        'Betun',
        'Ruteng',
        'Labuan Bajo',
        'Borong',
        'Mbay',
        'Bajawa',
        'Baa',
        'Seba',
        'Maumere',
        'Waikabubak',
        'Tambolaka',
        'Waibakul',
        'Waingapu',
        'Soe',
        'Kefamenanu',
        'Kupang'
    ],
    'Nusa Tenggara Timur' => [
        'Woha',
        'Kalabahi',
        'Atambua',
        'Ende',
        'Larantuka',
        'Oelamasi',
        'Lewoleba',
        'Betun',
        'Ruteng',
        'Labuan Bajo',
        'Borong',
        'Mbay',
        'Bajawa',
        'Baa',
        'Seba',
        'Maumere',
        'Waikabubak',
        'Tambolaka',
        'Waibakul',
        'Waingapu',
        'Soe',
        'Kefamenanu',
        'Kupang'
    ],
    'Kalimantan Barat' => [
        'Bengkayang',
        'Putussibau',
        'Sukadana',
        'Ketapang',
        'Sungai Raya',
        'Ngabang',
        'Nanga Pinoh',
        'Mempawah',
        'Sambas',
        'Sanggau',
        'Sekadau',
        'Sintang',
        'Pontianak',
        'Singkawang'
    ],
    'Kalimantan Tengah' => [
        'Buntok',
        'Tamiang Layang',
        'Muara Teweh',
        'Kuala Kurun',
        'Kuala Kapuas',
        'Kasongan',
        'Pangkalan Bun',
        'Sampit',
        'Bulik',
        'Puruk Cahu',
        'Sukamara',
        'Kuala Pembuang',
        'Palangka Raya'
    ],
    'Kalimantan Selatan' => [
        'Paringin',
        'Martapura',
        'Marabahan',
        'Kandangan',
        'Amuntai',
        'Kotabaru',
        'Tanjung',
        'Batulicin',
        'Pelaihari',
        'Rantau',
        'Banjarmasin',
        'Banjarbaru'
    ],
    'Kalimantan Timur' => [
        'Sendewar',
        'Tanjung Redeb',
        'Tenggarong',
        'Ujoh Bilang',
        'Penajam',
        'Samarinda'
    ],
    'Kalimantan Utara' => [
        'Tanjung Selor',
        'Malinau',
        'Nunukan',
        'Tandang Paler',
        'Tarakan'
    ],
    'Sulawesi Utara' => [
        'Tilamuta',
        'Suwawa',
        'Limboto',
        'Kwandang',
        'Marisa',
        'Kota Gorontalo',
        'Lolak',
        'Molibagu',
        'Tutuyan',
        'Boroko',
        'Tahuna',
        'Odong Siau',
        'Melonguane',
        'Tondano',
        'Amurang',
        'Rantahan',
        'Airmadidi',
        'Bitung',
        'Kotamobagu',
        'Manado',
        'Tomohon'
    ],
    'Sulawesi Tengah' => [
        'Luwuk',
        'Salakan',
        'Banggai',
        'Buol',
        'Banawa',
        'Bungku',
        'Kolonodale',
        'Parigi',
        'Poso',
        'Sigi Biromaru',
        'Ampana',
        'Tolitoli',
        'Palu'
    ],
    'Sulawesi Selatan' => [
        'Majene',
        'Mamasa',
        'Mamuju',
        'Tobadak',
        'Pasangkayu',
        'Polewali',
        'Barru',
        'Bantaeng',
        'Watampone',
        'Bulukumba',
        'Enrekang',
        'Sungguminasa',
        'Bontosunggu',
        'Benteng',
        'Belopa',
        'Malili',
        'Masamba',
        'Turikale',
        'Watang Sidenreng',
        'Balangnipa',
        'Watansoppeng',
        'Pattalassang',
        'Makale',
        'Rantepao',
        'Sengkang',
        'Makassar',
        'Palopo',
        'Parepare'
    ],
    'Sulawesi Tenggara' => [
        'Rumbia',
        'Pasarwajo',
        'Batauga',
        'Labungkari',
        'Buranga',
        'Kolaka',
        'Tirawuta',
        'Lasusua',
        'Unaaha',
        'Langara',
        'Andolo',
        'Wanggudu',
        'Raha',
        'Sawerigadi',
        'Wangi-wangi',
        'Bau-bau',
        'Kendari'
    ],
    'Gorontalo' => [
        'Tilamuta',
        'Suwawa',
        'Limboto',
        'Kwandang',
        'Marisa',
        'Kota Gorontalo'
    ],
    'Sulawesi Barat' => [
        'Majene',
        'Mamasa',
        'Mamuju',
        'Tobadak',
        'Pasangkayu',
        'Polewali'
    ],
    'Maluku' => [
        'Namlea',
        'Namrole',
        'Dobo',
        'Tiakur',
        'Masohi',
        'Langgur',
        'Saumlaki',
        'Piru',
        'Bula',
        'Ambon'
    ],
    'Maluku Utara' => [
        'Tuai',
        'Jailolo',
        'Weda',
        'Maba',
        'Labuha',
        'Tobelo',
        'Sanana',
        'Daruba',
        'Bobong',
        'Ternate',
        'Tidore'
    ],
    'Papua' => [
        'Agats',
        'Biak',
        'Tanah Merah',
        'Tigi',
        'Kigamani',
        'Sugapa',
        'Sentani',
        'Wamena',
        'Waris',
        'Serui',
        'Tiom',
        'Burmeso',
        'Kobakma',
        'Kepi',
        'Merauke',
        'Nabire',
        'Kenyam',
        'Enarotali',
        'Oksibil',
        'Ilaga',
        'Kotamulia',
        'Sarmi',
        'Sorendiweri',
        'Karubaga',
        'Botawa',
        'Sumohai',
        'Elelim',
        'Jayapura'
    ],
    'Papua Barat' => [
        'Fakfak',
        'Kaimana',
        'Manokwari',
        'Ransiki',
        'Kumurkek',
        'Anggi',
        'Waisai',
        'Aimas',
        'Teminabuan',
        'Bintuni',
        'Rasiei',
        'Sorong'
    ],
    'Papua Selatan' => [
        'Merauke',
        'Tanah Merah'
    ],
    'Papua Tengah' => [
        'Nabire',
        'Enarotali'
    ],
    'Papua Pegunungan' => [
        'Wamena',
        'Karubaga',
        'Oksibil'
    ],
    'Papua Barat Daya' => [
        'Fakfak',
        'Kaimana'
    ],
];
